---
title: '2021-03-02_Super Bowl Ads'
author: "YS"
date: "3/05/2021"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytuesdayR)
library(skimr)
library(scales)
library(here)
library(forcats)
library(tools)
tuesdata <- tidytuesdayR::tt_load('2021-03-02')
tuesdata <- tidytuesdayR::tt_load(2021, week = 10)

youtube <- tuesdata$youtube %>%
  select(-c(3, 4, 12, 13 ,14, 20, 21, 22, 23, 24))
```

```{r brand frequency}
freq_brand <- youtube %>%
  drop_na() %>%
  group_by(brand) %>%
  summarize(count = n(),
            comment_sum = sum(comment_count),
            like_sum = sum(like_count))%>%
  arrange(by = desc(count))

freq_brand$brand <- factor(freq_brand$brand)%>%
  fct_reorder(desc(freq_brand$count))
            
freq_brand %>%
  ggplot() +
  geom_col(aes(x = brand, y = count, fill = count)) +
  geom_point(aes(x = brand, y = comment_sum/100), color = "#669933") +
  geom_line(aes(x = brand, y = comment_sum/100, group = 1), color = "#669933") +
  geom_text(aes(label = count, x = brand, y = count), nudge_y = 3)+
  scale_y_continuous(
    name = "Frequency of Brand",
    sec.axis = sec_axis(~.*100, name="Culmilative Comment Number")
  ) +
  labs(title = "Brand Frequency and Comment number, 2000-2020")+
  xlab(label = "Brand")+
  theme_minimal()+
  theme(legend.position = "none",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = "#CCFFFF"),
        plot.title = element_text(size=14, face= "bold", colour= "black" ))
ggsave(here("Graphs", "2021-03-02", "brand_freq.png"),
       width = 9, height = 5.5, device = 'png')
```

```{r elements in ad}
el_ad <- youtube%>%
  select(c(1:9))%>%
  mutate(across(c(3:9), as.integer))%>%
# convert boolean TRUE/FALSE to 1/0
  group_by(brand)%>%
  summarise(count = n(),
            funny = sum(funny), 
            patriotic = sum(patriotic),
            celebrity = sum(celebrity),
            danger = sum(danger),
            animals = sum(animals),
            use_sex = sum(use_sex))
el_ad$brand <- factor(el_ad$brand)%>%
  fct_reorder(desc(el_ad$count))

#to long format
el_ad <- el_ad %>%
  pivot_longer(cols = -c(1, 2), names_to = "Element", values_to = "Count_el")
el_ad$Element[el_ad$Element == "use_sex"] <- "use sex"
el_ad$Element <- toTitleCase(el_ad$Element)

el_ad%>%
  ggplot(aes(x = brand, y = Count_el)) +
  geom_point(aes(color = count)) + 
  facet_wrap(~Element, nrow = 3, ncol = 2) + 
  geom_line(aes(group = 1)) +
  scale_x_discrete(guide = guide_axis(n.dodge = 3)) +
  labs(title = "Elements in Ad. by Brand, 2000-2020",
       subtitle = "Brand Ordered by Frequency")+
  xlab(label = "Brand")+
  ylab(label = "Count") +
  theme_minimal()+
  theme(legend.position = "none",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = "#CCFFFF"),
        plot.title = element_text(size=14, face= "bold", colour= "black" ))
ggsave(here("Graphs", "2021-03-02", "elem_freq.png"),
       width = 9, height = 5.5, device = 'png')
```

```{r like/dislike prop in view}
lpp <- youtube%>%
  select(c(2, 10, 11, 12))%>%
  drop_na()%>%
  group_by(brand)%>%
  summarise(count = n(),
            like = sum(like_count),
            dislike = sum(dislike_count),
            view = sum(view_count))%>%
  mutate(Like = (like)/(like + view) * 100,
         Dislike = dislike/(dislike + view) * 100)%>%
  mutate(lpp = str_c(as.character(round(Like, 2)), "%"), 
         dpp = str_c(as.character(round(Dislike, 2)), "%"))%>%
  select(-c(3, 4, 5))%>%
  pivot_longer(-c(1, 2 , 5, 6), names_to = "thumb", values_to = "Count_l")

lpp$brand <- factor(lpp$brand)%>%
  fct_reorder(desc(lpp$count))

lpp$thumb <- factor(lpp$thumb)%>%
  fct_relevel(c("Like", "Dislike"))
lpp$lpp[lpp$thumb == "Dislike"] <- NA
lpp$dpp[lpp$thumb == "Like"] <- NA

lpp%>%
  ggplot(aes(x = brand, y = Count_l, fill = thumb, group = thumb))+
  geom_col(position = "dodge") + 
  labs(title = "Percentage of Like/Dislike among culmilative Views, 2000-2020",
       subtitle = "Brand Ordered by Frequency")+
  xlab(label = "Brand")+
  ylab(label = "Percentage") +
  scale_fill_viridis_d() +
  theme_minimal()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = "#CCFFFF"),
        plot.title = element_text(size=14, face= "bold", colour= "black" ))
ggsave(here("Graphs", "2021-03-02", "like_rate.png"),
       width = 9, height = 5.5, device = 'png')
```

